project_id = "dxbdoqzwcyfivgblwsds"

[functions.send-access-code]
verify_jwt = false

[functions.send-document-notification]
verify_jwt = true

[functions.send-test-email]
verify_jwt = true

[functions.reset-subuser-password]
verify_jwt = true
